<?php

return array(

	/*
	|--------------------------------------------------------------------------
	| FlatTurtle ID
	|--------------------------------------------------------------------------
	*/

	'id' => 'flatturtle',


	/*
	|--------------------------------------------------------------------------
	| Template File
	|--------------------------------------------------------------------------
	|
	| The template file used to render the site. The default template is
	| sitecore::template. If you wish to use your own template file, override
	| this option with a valid template file, located in your app/views folder.
	|
	*/

	'template' => 'sitecore::template',


	/*
	|--------------------------------------------------------------------------
	| Mailchimp Form URL
	|--------------------------------------------------------------------------
	|
	| The Form URL can be found in the embedded form code generated by mailchimp.
	| Leave empty to disable mailchimp signup.
	|
	*/

	'mailchimp' => 'http://flatturtle.us6.list-manage.com/subscribe/post?u=d82ed07d6d647a768b87d3e8d&id=8de65c1467',


	/*
	|--------------------------------------------------------------------------
	| Google Analytics Account Code
	|--------------------------------------------------------------------------
	|
	| Leave empty to disable google analytics.
	|
	*/

	'analytics' => 'UA-31282630-1',


	/*
	|--------------------------------------------------------------------------
	| Social Media
	|--------------------------------------------------------------------------
	|
	| The key defines the icon that is used and the value is the corresponding
	| url. You can check the available icons at:
	| 	http://fortawesome.github.io/Font-Awesome/icons/#brand
	|
	| Example:
	|	'facebook' => 'https://www.facebook.com/pages/FlatTurtle/451854318217554'
	|
	*/

	'social' => array(
		'tumblr'	=>	'http://blog.flatturtle.com',
		'github'	=>	'https://github.com/FlatTurtle',
		'twitter'	=>	'https://twitter.com/FlatTurtle_',
		'linkedin'	=>	'http://www.linkedin.com/company/2493266',
	)

);